// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG3Xmi1bJawJT8p-yVcRtRbdf4TV6SfJ8',
    appId: '1:531885174144:web:d6f5f91142d2e786a52565',
    messagingSenderId: '531885174144',
    projectId: 'smart-ronda-ti-a0d83',
    authDomain: 'smart-ronda-ti-a0d83.firebaseapp.com',
    storageBucket: 'smart-ronda-ti-a0d83.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnkaHkoBqo5zoGNvGTyKboSm4ezwJYvfI',
    appId: '1:531885174144:android:f41029d86e589cb1a52565',
    messagingSenderId: '531885174144',
    projectId: 'smart-ronda-ti-a0d83',
    storageBucket: 'smart-ronda-ti-a0d83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVEOu3OUCmmrXeHLayzmwWSmSWnXTZ5w8',
    appId: '1:531885174144:ios:c21d6bfc3772e18ea52565',
    messagingSenderId: '531885174144',
    projectId: 'smart-ronda-ti-a0d83',
    storageBucket: 'smart-ronda-ti-a0d83.firebasestorage.app',
    iosBundleId: 'com.smartronda.ti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVEOu3OUCmmrXeHLayzmwWSmSWnXTZ5w8',
    appId: '1:531885174144:ios:c21d6bfc3772e18ea52565',
    messagingSenderId: '531885174144',
    projectId: 'smart-ronda-ti-a0d83',
    storageBucket: 'smart-ronda-ti-a0d83.firebasestorage.app',
    iosBundleId: 'com.smartronda.ti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG3Xmi1bJawJT8p-yVcRtRbdf4TV6SfJ8',
    appId: '1:531885174144:web:3eb58fc339368eaaa52565',
    messagingSenderId: '531885174144',
    projectId: 'smart-ronda-ti-a0d83',
    authDomain: 'smart-ronda-ti-a0d83.firebaseapp.com',
    storageBucket: 'smart-ronda-ti-a0d83.firebasestorage.app',
  );
}
